/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef SDK_PROJECT_CONFIG_H_
#define SDK_PROJECT_CONFIG_H_


/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/* Include header files for all configured components */
#include "clock_config.h"
#include "pin_mux.h"
#include "peripherals_edma_config_1.h"
#include "peripherals_osif_1.h"
#include "peripherals_flash_1.h"
#include "peripherals_lpspi_1.h"
#include "peripherals_lpi2c_config_1.h"
#include "peripherals_ewm_config_1.h"
#include "peripherals_pdb_config_1.h"
#include "peripherals_rtc_1.h"
#include "peripherals_flexcan_config_1.h"
#include "peripherals_lpuart_1.h"
#include "peripherals_flexio_spi_config_1.h"
#include "peripherals_wdog_config_1.h"
#include "peripherals_crc_1.h"
#include "peripherals_lptmr_1.h"
#include "peripherals_flexio_i2c_config_1.h"
#include "peripherals_erm_config_1.h"
#include "peripherals_cmp_1.h"
#include "peripherals_flexio_uart_config_1.h"
#include "peripherals_eim_config_1.h"
#include "peripherals_lpit_config_1.h"
#include "peripherals_flexio_i2s_config_1.h"
#include "peripherals_trgmux_1.h"
#include "peripherals_adc_config_1.h"
#include "peripherals_csec_config_1.h"
#include "peripherals_power_manager_1.h"
#include "peripherals_mpu_config_1.h"


#endif /* SDK_PROJECT_CONFIG_H_ */

